// Iranian Foods
export const iranianFoodInformation = [
  {
    id: 1,
    image: "assets/images/foodImages/iranian_food/iranian_food_01.png",
    title: "کوفته برنجی",
    description: "برنج سبزی کوفته لپه آرد نخودچی، گردو و زرشک و آلو پیاز",
    highPrice: "۱۸۰٬۰۰۰",
    discount: "%۳۵",
    discountedPrice: "۱۴۵٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 2,
    image: "assets/images/foodImages/iranian_food/iranian_food_02.png",
    title: "کشک بادمجان",
    description: "بادمجان، کشک، نعناع خشک، مغز گردو، سیر، پیاز",
    highPrice: "",
    discount: "",
    discountedPrice: "۹۵٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 3,
    image: "assets/images/foodImages/iranian_food/iranian_food_03.png",
    title: "میرزا قاسمی",
    description: "بادمجان، گوجه فرنگی، تخم مرغ، سیر، رب گوجه فرنگی",
    highPrice: "۱۶۵٬۰۰۰",
    discount: "%۱۰",
    discountedPrice: "۱۴۲٬۵۰۰  تومان",
    star: "some star",
  },
  {
    id: 4,
    image: "assets/images/foodImages/iranian_food/iranian_food_04.png",
    title: "باقلاقاتوق",
    description: "پاچ باقلا، شوید خشک، کره، سیر، تخم مرغ",
    highPrice: "۲۰۵٬۰۰۰",
    discount: "%۳۰",
    discountedPrice: "۱۸۰٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 5,
    image: "assets/images/foodImages/iranian_food/iranian_food_05.png",
    title: "فلافل",
    description: "نخود، پیاز، تخم گشنیز، سیر، جعفری، سیب زمینی",
    highPrice: "",
    discount: "",
    discountedPrice: "۸۰٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 6,
    image: "assets/images/foodImages/iranian_food/iranian_food_06.png",
    title: "کله جوش",
    description: "کشک، گردو، پیاز، نعناع خشک",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۵",
    discountedPrice: "۲۰۳٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 7,
    image: "assets/images/foodImages/iranian_food/iranian_food_07.png",
    title: "بورانی بادمجان",
    description: "بادمجان قلمی، ماست چکیده، سیر، روغن زیتون، مغز گردو",
    highPrice: "۱۷۰٬۰۰۰",
    discount: "%۲۲",
    discountedPrice: "۱۴۸٬۰۰۰ تومان",
    star: "some star",
    score: "(۷۵ امتیاز)",
  },
  {
    id: 8,
    image: "assets/images/foodImages/iranian_food/iranian_food_08.png",
    title: "بادمجان شکم‌پر",
    description: "بادمجان، پیاز، گوجه فرنگی	، سبزی خشک",
    highPrice: "۱۵۰٬۰۰۰",
    discount: "%۱۸",
    discountedPrice: "۱۳۶٬۰۰۰ تومان",
    star: "some star",
    score: "(۳۲ امتیاز)",
  },
  {
    id: 9,
    image: "assets/images/foodImages/iranian_food/iranian_food_09.png",
    title: "دلمه برگ کلم",
    description: "کلم برگ، برنج، لپه پخته، پیاز، سبزی معطر رب",
    highPrice: "۲۲۰٬۰۰۰",
    discount: "%۸",
    discountedPrice: "۲۰۹٬۰۰۰ تومان",
    star: "some star",
    score: "(۵۲ امتیاز)",
  },
  {
    id: 10,
    image: "assets/images/foodImages/iranian_food/iranian_food_10.png",
    title: "دلمه برگ مو",
    description: "پیاز، برنج، لپه، سبزی دلمه، سرکه",
    highPrice: "",
    discount: "",
    discountedPrice: "۱۹۵٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 11,
    image: "assets/images/foodImages/iranian_food/iranian_food_11.png",
    title: "کوکو سبزی",
    description: "تخم مرغ، گردو، سیر، آرد، روغن مایع سبزی کوکویی",
    highPrice: "۳۰۰٬۰۰۰",
    discount: "%۱۰",
    discountedPrice: "۲۷۰٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 12,
    image: "assets/images/foodImages/iranian_food/iranian_food_12.png",
    title: "کوکو سیب‌زمینی و عدس",
    description: "عدس، سیب زمینی، پیاز متوسط، تخم مرغ، پودر سیر، آرد سوخاری",
    highPrice: "۱۳۵٬۰۰۰",
    discount: "%۲۰",
    discountedPrice: "۱۰۵٬۰۰۰ تومان",
    star: "some star",
  },
];

// Not Iranian Foods
export const notIranianFoodInformation = [
  {
    id: 1,
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_01.png",
    title: "پاستا سبزیجات",
    description: "پاستا، قارچ، گوجه، کدوی خوردشده، پیاز خلالی‌شده",
    highPrice: "۱۷۵٬۰۰۰",
    discount: "%۲۰",
    discountedPrice: "۱۴۰٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 2,
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_02.png",
    title: "پاستا بلونز",
    description:
      "اسپاگتی، گوشت چرخ کرده، هویج، ساقه کرفس، گوجه فرنگی، سیر، پیاز، پنیر پارمزان",
    highPrice: "۱۷۰٬۰۰۰",
    discount: "%۱۲",
    discountedPrice: "۱۶۰٬۰۰۰  تومان",
    star: "some star",
  },
  {
    id: 3,
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_03.png",
    title: "راتاتویی",
    description:
      "بادمجان، گوجه فرنگی، کدو سبز، پیاز، رب گوجه فرنگی، روغن زیتون، پنیر پارمزان",
    highPrice: "۱۸۰٬۰۰۰",
    discount: "%۴۵",
    discountedPrice: "۹۵٬۰۰۰ تومان",
    star: "some star",
    score: "(۴۳ امتیاز)",
  },
  {
    id: 4,
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_04.png",
    title: "لازانیا",
    description:
      "لازانیا، قارچ، ریحان تازه، جعفری تازه، گوجه فرنگی، پنیر پیتزا، بادمجان",
    highPrice: "",
    discount: "",
    discountedPrice: "۱۵۰٬۰۰۰ تومان",
    star: "some star",
    score: "(۴۸ امتیاز)",
  },
  {
    id: 5,
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_05.png",
    title: "سوشی",
    description:
      "جلبک دریایی/ نوری، برنج کته، سرکه سفید (یا سرکه برنج)، شکر، نمک دریا",
    highPrice: "۱۰۰٬۰۰۰",
    discount: "%۱۵",
    discountedPrice: "۸۵٬۰۰۰ تومان",
    star: "some star",
    score: "(۷۰ امتیاز)",
  },
  {
    id: 6,
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_06.png",
    title: "پاکورا سبزیجات",
    description: "گرام ماسالا، پودر کاری، سیر له شده، ،گشنیز خرد شده",
    highPrice: "۱۲۵٬۰۰۰",
    discount: "%۸",
    discountedPrice: "۱۱۰٬۰۰۰ تومان",
    star: "some star",
    score: "(۷۵ امتیاز)",
  },
  {
    id: 7,
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_07.png",
    title: "کالزونه اسفناج",
    description:
      "اسفناج، قارچ، پنیر موزارلا یا پنیر پیتزا، پنیر ریکوتا یا پنیر خامه ای، پیاز، سیر، روغن زیتون",
    highPrice: "۱۹۰٬۰۰۰",
    discount: "%۱۷",
    discountedPrice: "۱۷۷٬۰۰۰ تومان",
    star: "some star",
    score: "(۶۲ امتیاز)",
  },
  {
    id: 8,
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_08.png",
    title: "پالاک پنیر ",
    description: "پنیر، اسفناج، گوجه، پیاز، سیر ",
    highPrice: "۲۰۰٬۰۰۰",
    discount: "%۱۵",
    discountedPrice: "۱۸۰٬۰۰۰ تومان",
    star: "some star",
  },
];

// Pizzas
export const pizzaInformation = [
  {
    id: 1,
    image: "assets/images/foodImages/pizza/pizza_01.png",
    title: "پیتزا روکولا",
    description:
      "اسفناج، سبزی روکولا، آرد، پودر مایه خمیر، روغن زیتون، خردل، سیر، پنیر موزارلا و ",
    highPrice: "۱۹۵٬۰۰۰",
    discount: "%۱۲",
    discountedPrice: "۱۸۸٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 2,
    image: "assets/images/foodImages/pizza/pizza_02.png",
    title: "پیتزا بادمجان و زیتون",
    description:
      "بادمجان کوچک، روغن زیتون، پنیر موزارلا، پنیر پارمزان، برگ ریحان، گوجه فرنگی، سس گوجه فرنگی",
    highPrice: "",
    discount: "",
    discountedPrice: "۱۵۰٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 3,
    image: "assets/images/foodImages/pizza/pizza_03.png",
    title: "پیتزا سبزیجات و خامه",
    description:
      "نخود فرنگی پخته شده، ذرت نیم پز، فلفل دلمه‌ای رنگی، قارچ، سیر یا پیازچه خردشده",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۲۱",
    discountedPrice: "۱۸۵٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 4,
    image: "assets/images/foodImages/pizza/pizza_04.png",
    title: "پیتزا قارچ",
    description:
      "قارچ، فلفل دلمه ای، رب گوجه فرنگی، پودر سیر، آویشن، مرزه، پنیر پیتزا گیاهی",
    highPrice: "۲۱۵٬۰۰۰",
    discount: "%۲۵",
    discountedPrice: "۱۷۵٬۰۰۰ تومان",
    star: "some star",
    score: "(۳۳ امتیاز)",
  },
  {
    id: 5,
    image: "assets/images/foodImages/pizza/pizza_05.png",
    title: "پیتزا پپرونی",
    description:
      "تافو، فلفل قرمز خشک شده، پودر دانه‌های خردل، دانه رازیانه، پاپریکا دودی، پودر سیر، شکر نارگیل، پودر بادیان رومی ",
    highPrice: "",
    discount: "",
    discountedPrice: "۱۰۰٬۰۰۰ تومان",
    star: "some star",
    score: "(۵۱ امتیاز)",
  },
  {
    id: 6,
    image: "assets/images/foodImages/pizza/pizza_06.png",
    title: "پیتزا اسفناج",
    description: "اسفناج تازه، پیاز، سیر، پنیر پیتزا، قارچ",
    highPrice: "۲۸۰٬۰۰۰",
    discount: "%۱۰",
    discountedPrice: "۲۵۲٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 7,
    image: "assets/images/foodImages/pizza/pizza_07.png",
    title: "پیتزا مارگاریتا",
    description: "گوجه فرنگی، ریحان، سیر، پنیر پیتزا",
    highPrice: "۱۶۵٬۰۰۰",
    discount: "%۱۳",
    discountedPrice: "۱۴۷٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 8,
    image: "assets/images/foodImages/pizza/pizza_08.png",
    title: "پیتزا پنیر",
    description:
      "نان پیتزا، پنیر پیتزا، سس باربیکیو، گوجه فرنگی، سس کچاپ، سیر، روغن زیتون",
    highPrice: "۱۲۵٬۰۰۰",
    discount: "%۱۶",
    discountedPrice: "۱۰۵٬۰۰۰  تومان",
    star: "some star",
  },
];

// Sandwiches
export const sandwichesInformation = [
  {
    id: 1,
    image: "assets/images/foodImages/sandwich/sandwich_01.png",
    title: "ساندویچ کتلت مخصوص",
    description:
      "سیب زمینی، لوبیا قرمز،  بلغور گندم، نعناع خشک، پودر زیره، پودر جوز هندی، گوجه فرنگی، روغن زیتون",
    highPrice: "۲۳۰٬۰۰۰",
    discount: "%۱۸",
    discountedPrice: "۲۰۵٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 2,
    image: "assets/images/foodImages/sandwich/sandwich_02.png",
    title: "ساندویچ سوسیس کوکتل",
    description: "سوسیس گیاهی، پیاز، سیب زمینی،  رب گوجه فرنگی",
    highPrice: "۲۰۵٬۰۰۰",
    discount: "%۳۵",
    discountedPrice: "۱۶۵٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 3,
    image: "assets/images/foodImages/sandwich/sandwich_03.png",
    title: "ساندویچ کتلت کدو سبز",
    description: "کدو سبز، هویج، سیب زمینی، پیاز",
    highPrice: "",
    discount: "",
    discountedPrice: "۱۴۵٬۰۰۰ تومان",
    star: "some star",
  },
  {
    id: 4,
    image: "assets/images/foodImages/sandwich/sandwich_04.png",
    title: "پنینی اسفناج",
    description:
      " قارچ، اسفناج، پیاز، پنیر پیتزا، خامه، پودر پاپریکا، گردو، سرکه بالزامیک، سس مایونز",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۱۵",
    discountedPrice: "۱۹۰٬۰۰۰ تومان",
    star: "some star",
    score: "(۲۰ امتیاز)",
  },
];

// Branches
export const branchesInformation = [
  {
    id: 1,
    image: "assets/images/branchImages/branch_01.png",
    title: "شعبه اکباتان",
    description: "شهرک اکباتان، فاز ۳، مجتمع تجاری کوروش، طبقه سوم",
  },
  {
    id: 2,
    image: "assets/images/branchImages/branch_02.png",
    title: "شعبه چالوس",
    description:
      "چالوس، خیابان ۱۷ شهریور، بعد کوچه کوروش، جنب داروخانه دکتر میلانی، رستوران ترخینه",
  },
  {
    id: 3,
    image: "assets/images/branchImages/branch_03.png",
    title: "شعبه اقدسیه",
    description: "خیابان اقدسیه ، نرسیده به میدان خیام، پلاک ۸",
  },
  {
    id: 4,
    image: "assets/images/branchImages/branch_04.png",
    title: "شعبه ونک",
    description: "میدان ونک، خیابان فردوسی، نبش کوچه نیلوفر، پلاک ۲۶",
  },
];

// Navbar
export const navbarItems = [
  {
    id: 1,
    text: "صفحه اصلی",
    icon: false,
  },
  {
    id: 2,
    text: "شعبه",
    icon: true,
  },
  {
    id: 3,
    text: "منو",
    icon: true,
  },
  {
    id: 4,
    text: "اعطای نمایندگی",
    icon: false,
  },
  {
    id: 5,
    text: "درباره ما",
    icon: false,
  },
  {
    id: 6,
    text: "تماس با ما",
    icon: false,
  },
];
