import ShoppingCartOutlinedIcon from "@mui/icons-material/ShoppingCartOutlined";
import SearchOutlinedIcon from "@mui/icons-material/SearchOutlined";
import PersonOutlineOutlinedIcon from "@mui/icons-material/PersonOutlineOutlined";

// Iranian Foods
export const foodInformation = [
  {
    id: 1,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_01.png",
    title: "کوفته برنجی",
    description: "برنج سبزی کوفته لپه آرد نخودچی، گردو و زرشک و آلو پیاز",
    highPrice: "۱۸۰٬۰۰۰",
    discount: "%۳۵",
    // finalPrice: "۱۴۵٬۰۰۰ تومان",
    finalPrice: 145000,
    star: "some star",
  },
  {
    id: 2,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_02.png",
    title: "کشک بادمجان",
    description: "بادمجان، کشک، نعناع خشک، مغز گردو، سیر، پیاز",
    highPrice: "",
    // discount: "",
    // finalPrice: "۹۵٬۰۰۰ تومان",
    finalPrice: 95000,
    star: "some star",
  },
  {
    id: 3,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_03.png",
    title: "میرزا قاسمی",
    description: "بادمجان، گوجه فرنگی، تخم مرغ، سیر، رب گوجه فرنگی",
    highPrice: "۱۶۵٬۰۰۰",
    discount: "%۱۰",
    // finalPrice: "۱۴۲٬۵۰۰  تومان",
    finalPrice: 142500,
    star: "some star",
  },
  {
    id: 4,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_04.png",
    title: "باقلاقاتوق",
    description: "پاچ باقلا، شوید خشک، کره، سیر، تخم مرغ",
    highPrice: "۲۰۵٬۰۰۰",
    discount: "%۳۰",
    // finalPrice: "۱۸۰٬۰۰۰ تومان",
    finalPrice: 180000,
    star: "some star",
  },
  {
    id: 5,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_05.png",
    title: "فلافل",
    description: "نخود، پیاز، تخم گشنیز، سیر، جعفری، سیب زمینی",
    highPrice: "",
    // discount: "",
    // finalPrice: "۸۰٬۰۰۰ تومان",
    finalPrice: 80000,
    star: "some star",
  },
  {
    id: 6,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_06.png",
    title: "کله جوش",
    description: "کشک، گردو، پیاز، نعناع خشک",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۵",
    // finalPrice: "۲۰۳٬۰۰۰ تومان",
    finalPrice: 203000,
    star: "some star",
  },
  {
    id: 7,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_07.png",
    title: "بورانی بادمجان",
    description: "بادمجان قلمی، ماست چکیده، سیر، روغن زیتون، مغز گردو",
    highPrice: "۱۷۰٬۰۰۰",
    discount: "%۲۲",
    // finalPrice: "۱۴۸٬۰۰۰ تومان",
    finalPrice: 148000,
    star: "some star",
    score: "(۷۵ امتیاز)",
  },
  {
    id: 8,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_08.png",
    title: "بادمجان شکم‌پر",
    description: "بادمجان، پیاز، گوجه فرنگی	، سبزی خشک",
    highPrice: "۱۵۰٬۰۰۰",
    discount: "%۱۸",
    // finalPrice: "۱۳۶٬۰۰۰ تومان",
    finalPrice: 136000,
    star: "some star",
    score: "(۳۲ امتیاز)",
  },
  {
    id: 9,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_09.png",
    title: "دلمه برگ کلم",
    description: "کلم برگ، برنج، لپه پخته، پیاز، سبزی معطر رب",
    highPrice: "۲۲۰٬۰۰۰",
    discount: "%۸",
    // finalPrice: "۲۰۹٬۰۰۰ تومان",
    finalPrice: 209000,
    star: "some star",
    score: "(۵۲ امتیاز)",
  },
  {
    id: 10,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_10.png",
    title: "دلمه برگ مو",
    description: "پیاز، برنج، لپه، سبزی دلمه، سرکه",
    highPrice: "",
    // discount: "",
    // finalPrice: "۱۹۵٬۰۰۰ تومان",
    finalPrice: 195000,
    star: "some star",
  },
  {
    id: 11,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_11.png",
    title: "کوکو سبزی",
    description: "تخم مرغ، گردو، سیر، آرد، روغن مایع سبزی کوکویی",
    highPrice: "۳۰۰٬۰۰۰",
    discount: "%۱۰",
    // finalPrice: "۲۷۰٬۰۰۰ تومان",
    finalPrice: 270000,
    star: "some star",
  },
  {
    id: 12,
    category: "غذاهای ایرانی",
    image: "assets/images/foodImages/iranian_food/iranian_food_12.png",
    title: "کوکو سیب‌زمینی و عدس",
    description: "عدس، سیب زمینی، پیاز متوسط، تخم مرغ، پودر سیر، آرد سوخاری",
    highPrice: "۱۳۵٬۰۰۰",
    discount: "%۲۰",
    // finalPrice: "۱۰۵٬۰۰۰ تومان",
    finalPrice: 105000,
    star: "some star",
  },

  // Not Iranian Foods
  {
    id: 13,
    category: "غذاهای غیر ایرانی",
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_01.png",
    title: "پاستا سبزیجات",
    description: "پاستا، قارچ، گوجه، کدوی خوردشده، پیاز خلالی‌شده",
    highPrice: "۱۷۵٬۰۰۰",
    discount: "%۲۰",
    // finalPrice: "۱۴۰٬۰۰۰ تومان",
    finalPrice: 140000,
    star: "some star",
  },
  {
    id: 14,
    category: "غذاهای غیر ایرانی",
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_02.png",
    title: "پاستا بلونز",
    description:
      "اسپاگتی، گوشت چرخ کرده، هویج، ساقه کرفس، گوجه فرنگی، سیر، پیاز، پنیر پارمزان",
    highPrice: "۱۷۰٬۰۰۰",
    discount: "%۱۲",
    // finalPrice: "۱۶۰٬۰۰۰  تومان",
    finalPrice: 160000,
    star: "some star",
  },
  {
    id: 15,
    category: "غذاهای غیر ایرانی",
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_03.png",
    title: "راتاتویی",
    description:
      "بادمجان، گوجه فرنگی، کدو سبز، پیاز، رب گوجه فرنگی، روغن زیتون، پنیر پارمزان",
    highPrice: "۱۸۰٬۰۰۰",
    discount: "%۴۵",
    // finalPrice: "۹۵٬۰۰۰ تومان",
    finalPrice: 95000,
    star: "some star",
    score: "(۴۳ امتیاز)",
  },
  {
    id: 16,
    category: "غذاهای غیر ایرانی",
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_04.png",
    title: "لازانیا",
    description:
      "لازانیا، قارچ، ریحان تازه، جعفری تازه، گوجه فرنگی، پنیر پیتزا، بادمجان",
    highPrice: "",
    // discount: "",
    // finalPrice: "۱۵۰٬۰۰۰ تومان",
    finalPrice: 150000,
    star: "some star",
    score: "(۴۸ امتیاز)",
  },
  {
    id: 17,
    category: "غذاهای غیر ایرانی",
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_05.png",
    title: "سوشی",
    description:
      "جلبک دریایی/ نوری، برنج کته، سرکه سفید (یا سرکه برنج)، شکر، نمک دریا",
    highPrice: "۱۰۰٬۰۰۰",
    discount: "%۱۵",
    // finalPrice: "۸۵٬۰۰۰ تومان",
    finalPrice: 85000,
    star: "some star",
    score: "(۷۰ امتیاز)",
  },
  {
    id: 18,
    category: "غذاهای غیر ایرانی",
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_06.png",
    title: "پاکورا سبزیجات",
    description: "گرام ماسالا، پودر کاری، سیر له شده، ،گشنیز خرد شده",
    highPrice: "۱۲۵٬۰۰۰",
    discount: "%۸",
    // finalPrice: "۱۱۰٬۰۰۰ تومان",
    finalPrice: 110000,
    star: "some star",
    score: "(۷۵ امتیاز)",
  },
  {
    id: 19,
    category: "غذاهای غیر ایرانی",
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_07.png",
    title: "کالزونه اسفناج",
    description:
      "اسفناج، قارچ، پنیر موزارلا یا پنیر پیتزا، پنیر ریکوتا یا پنیر خامه ای، پیاز، سیر، روغن زیتون",
    highPrice: "۱۹۰٬۰۰۰",
    discount: "%۱۷",
    // finalPrice: "۱۷۷٬۰۰۰ تومان",
    finalPrice: 177000,
    star: "some star",
    score: "(۶۲ امتیاز)",
  },
  {
    id: 20,
    category: "غذاهای غیر ایرانی",
    image: "assets/images/foodImages/not_iranian_food/not_iranian_food_08.png",
    title: "پالاک پنیر ",
    description: "پنیر، اسفناج، گوجه، پیاز، سیر ",
    highPrice: "۲۰۰٬۰۰۰",
    discount: "%۱۵",
    // finalPrice: "۱۸۰٬۰۰۰ تومان",
    finalPrice: 180000,
    star: "some star",
  },

  // Pizzas
  {
    id: 21,
    category: "پیتزاها",
    image: "assets/images/foodImages/pizza/pizza_01.png",
    title: "پیتزا روکولا",
    description:
      "اسفناج، سبزی روکولا، آرد، پودر مایه خمیر، روغن زیتون، خردل، سیر، پنیر موزارلا و ",
    highPrice: "۱۹۵٬۰۰۰",
    discount: "%۱۲",
    // finalPrice: "۱۸۸٬۰۰۰ تومان",
    finalPrice: 188000,
    star: "some star",
  },
  {
    id: 22,
    category: "پیتزاها",
    image: "assets/images/foodImages/pizza/pizza_02.png",
    title: "پیتزا بادمجان و زیتون",
    description:
      "بادمجان کوچک، روغن زیتون، پنیر موزارلا، پنیر پارمزان، برگ ریحان، گوجه فرنگی، سس گوجه فرنگی",
    highPrice: "",
    // discount: "",
    // finalPrice: "۱۵۰٬۰۰۰ تومان",
    finalPrice: 150000,
    star: "some star",
  },
  {
    id: 23,
    category: "پیتزاها",
    image: "assets/images/foodImages/pizza/pizza_03.png",
    title: "پیتزا سبزیجات و خامه",
    description:
      "نخود فرنگی پخته شده، ذرت نیم پز، فلفل دلمه‌ای رنگی، قارچ، سیر یا پیازچه خردشده",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۲۱",
    // finalPrice: "۱۸۵٬۰۰۰ تومان",
    finalPrice: 185000,
    star: "some star",
  },
  {
    id: 24,
    category: "پیتزاها",
    image: "assets/images/foodImages/pizza/pizza_04.png",
    title: "پیتزا قارچ",
    description:
      "قارچ، فلفل دلمه ای، رب گوجه فرنگی، پودر سیر، آویشن، مرزه، پنیر پیتزا گیاهی",
    highPrice: "۲۱۵٬۰۰۰",
    discount: "%۲۵",
    // finalPrice: "۱۷۵٬۰۰۰ تومان",
    finalPrice: 175000,
    star: "some star",
    score: "(۳۳ امتیاز)",
  },
  {
    id: 25,
    category: "پیتزاها",
    image: "assets/images/foodImages/pizza/pizza_05.png",
    title: "پیتزا پپرونی",
    description:
      "تافو، فلفل قرمز خشک شده، پودر دانه‌های خردل، دانه رازیانه، پاپریکا دودی، پودر سیر، شکر نارگیل، پودر بادیان رومی ",
    highPrice: "",
    // discount: "",
    // finalPrice: "۱۰۰٬۰۰۰ تومان",
    finalPrice: 100000,
    star: "some star",
    score: "(۵۱ امتیاز)",
  },
  {
    id: 26,
    category: "پیتزاها",
    image: "assets/images/foodImages/pizza/pizza_06.png",
    title: "پیتزا اسفناج",
    description: "اسفناج تازه، پیاز، سیر، پنیر پیتزا، قارچ",
    highPrice: "۲۸۰٬۰۰۰",
    discount: "%۱۰",
    // finalPrice: "۲۵۲٬۰۰۰ تومان",
    finalPrice: 252000,
    star: "some star",
  },
  {
    id: 27,
    category: "پیتزاها",
    image: "assets/images/foodImages/pizza/pizza_07.png",
    title: "پیتزا مارگاریتا",
    description: "گوجه فرنگی، ریحان، سیر، پنیر پیتزا",
    highPrice: "۱۶۵٬۰۰۰",
    discount: "%۱۳",
    // finalPrice: "۱۴۷٬۰۰۰ تومان",
    finalPrice: 147000,
    star: "some star",
  },
  {
    id: 28,
    category: "پیتزاها",
    image: "assets/images/foodImages/pizza/pizza_08.png",
    title: "پیتزا پنیر",
    description:
      "نان پیتزا، پنیر پیتزا، سس باربیکیو، گوجه فرنگی، سس کچاپ، سیر، روغن زیتون",
    highPrice: "۱۲۵٬۰۰۰",
    discount: "%۱۶",
    // finalPrice: "۱۰۵٬۰۰۰  تومان",
    finalPrice: 105000,
    star: "some star",
  },

  // Sandwiches
  {
    id: 29,
    category: "ساندویچ‌ها",
    image: "assets/images/foodImages/sandwich/sandwich_01.png",
    title: "ساندویچ کتلت مخصوص",
    description:
      "سیب زمینی، لوبیا قرمز،  بلغور گندم، نعناع خشک، پودر زیره، پودر جوز هندی، گوجه فرنگی، روغن زیتون",
    highPrice: "۲۳۰٬۰۰۰",
    discount: "%۱۸",
    // finalPrice: "۲۰۵٬۰۰۰ تومان",
    finalPrice: 205000,
    star: "some star",
  },
  {
    id: 30,
    category: "ساندویچ‌ها",
    image: "assets/images/foodImages/sandwich/sandwich_02.png",
    title: "ساندویچ سوسیس",
    description: "سوسیس گیاهی، پیاز، سیب زمینی،  رب گوجه فرنگی",
    highPrice: "۲۰۵٬۰۰۰",
    discount: "%۳۵",
    // finalPrice: "۱۶۵٬۰۰۰ تومان",
    finalPrice: 165000,
    star: "some star",
  },
  {
    id: 31,
    category: "ساندویچ‌ها",
    image: "assets/images/foodImages/sandwich/sandwich_03.png",
    title: "ساندویچ کتلت کدو سبز",
    description: "کدو سبز، هویج، سیب زمینی، پیاز",
    highPrice: "",
    // discount: "",
    // finalPrice: "۱۴۵٬۰۰۰ تومان",
    finalPrice: 145000,
    star: "some star",
  },
  {
    id: 32,
    category: "ساندویچ‌ها",
    image: "assets/images/foodImages/sandwich/sandwich_04.png",
    title: "پنینی اسفناج",
    description:
      " قارچ، اسفناج، پیاز، پنیر پیتزا، خامه، پودر پاپریکا، گردو، سرکه بالزامیک، سس مایونز",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۱۵",
    // finalPrice: "۱۹۰٬۰۰۰ تومان",
    finalPrice: 190000,
    star: "some star",
    score: "(۲۰ امتیاز)",
  },
  {
    id: 33,
    category: "ساندویچ‌ها",
    image: "assets/images/foodImages/sandwich/sandwich_04.png",
    title: "ساندویچ همبرگر",
    description: " قارچ، پیاز، پنیر پیتزا، گردو، سرکه بالزامیک، سس مایونز",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۱۵",
    // finalPrice: "۱۹۰٬۰۰۰ تومان",
    finalPrice: 190000,
    star: "some star",
    score: "(۲۰ امتیاز)",
  },
];

// Not Iranian Foods
// export const notIranianFoodInformation = [];

// Pizzas
// export const pizzaInformation = [];

// Sandwiches
// export const sandwichesInformation = [];

// Branches
export const branchesInformation = [
  {
    id: 1,
    image: "assets/images/branchImages/branch_01.png",
    title: "شعبه اکباتان",
    address: "شهرک اکباتان، فاز ۳، مجتمع تجاری کوروش، طبقه سوم",
    phoneNumber: "۰۲۱-۵۴۸۹۱۲۵۰-۵۱",
    workTime: "همه روزه از ساعت 12 تا 23 بجز روزهای تعطیل",
  },
  {
    id: 2,
    image: "assets/images/branchImages/branch_02.png",
    title: "شعبه چالوس",
    address: "چالوس، خیابان ۱۷ شهریور، بعد کوچه کوروش، جنب داروخانه",
    phoneNumber: "۰۲۱-۵۴۸۹۱۲۵۲-۵۳",
    workTime: "همه روزه از ساعت 12 تا 23 بجز روزهای تعطیل",
  },
  {
    id: 3,
    image: "assets/images/branchImages/branch_03.png",
    title: "شعبه اقدسیه",
    address: "خیابان اقدسیه ، نرسیده به میدان خیام، پلاک ۸",
    phoneNumber: "۰۲۱-۵۴۸۹۱۲۵۴-۵۵",
    workTime: "همه روزه از ساعت 12 تا 23 بجز روزهای تعطیل",
  },
  {
    id: 4,
    image: "assets/images/branchImages/branch_04.png",
    title: "شعبه ونک",
    address: "میدان ونک، خیابان فردوسی، نبش کوچه نیلوفر، پلاک ۲۶",
    phoneNumber: "۰۲۱-۵۴۸۹۱۲۵۶-۵۷",
    workTime: "همه روزه از ساعت 12 تا 23 بجز روزهای تعطیل",
  },
];

// Navbar
export const navbarItems = [
  {
    id: 1,
    text: "صفحه اصلی",
    path: "/",
    image: "assets/images/icons/home.png",
  },
  {
    id: 2,
    text: "شعبه",
    icon: "assets/images/icons/arrow-down.png",
    path: "/branch",
    image: "assets/images/icons/menu-board_02.png",
  },
  {
    id: 3,
    text: "منو",
    icon: "assets/images/icons/arrow-down.png",
    path: "/menu",
    image: "assets/images/icons/home-hashtag.png",
  },
  {
    id: 4,
    text: "اعطای نمایندگی",
    path: "/franchise",
    image: "assets/images/icons/diagram_02.png",
  },
  {
    id: 5,
    text: "درباره ما",
    path: "/aboutUs",
    image: "assets/images/icons/profile-2user.png",
  },
  {
    id: 6,
    text: "تماس با ما",
    path: "/contact",
    image: "assets/images/icons/call-calling.png",
  },
];

// navbar icons

export const navbarIcons = [
  {
    id: 1,
    icons: "assets/images/icons/search-normal-01.png",
    iconsWhite: "assets/images/icons/shopping-cart_white.png",
    path: "/search",
  },
  {
    id: 2,
    icons: "assets/images/icons/shopping-cart.png",
    iconsWhite: "assets/images/icons/shopping-cart_white.png",
    path: "/cart",
  },
  {
    id: 3,
    icons: "assets/images/icons/user.png",
    iconsWhite: "assets/images/icons/user_02.png",
    path: "/userProfile",
  },
];

// Banner
export const bannerInformation = [
  {
    id: 1,
    image: "assets/images/bannerImages/slider_01.png",
    text: "تجربه غذای سالم و گیاهی به سبک ترخینه",
  },
  {
    id: 2,
    image: "assets/images/bannerImages/slider_02.png",
    text: "طعم بی‌نظیر طبیعت!",
  },
  {
    id: 3,
    image: "assets/images/bannerImages/slider_03.png",
    text: "لذت غذای سالم و گیاهی را با ترخینه تجربه کنید!",
  },
  {
    id: 4,
    image: "assets/images/bannerImages/slider_01.png",
    text: "تجربه غذای سالم و گیاهی به سبک ترخینه",
  },
  {
    id: 5,
    image: "assets/images/bannerImages/slider_02.png",
    text: "طعم بی‌نظیر طبیعت!",
  },
  {
    id: 6,
    image: "assets/images/bannerImages/slider_03.png",
    text: "لذت غذای سالم و گیاهی را با ترخینه تجربه کنید!",
  },
];

// Menu Component
export const menuInformation = [
  {
    id: 1,
    image: "assets/images/firstPageImages/01.png",
    text: "غذای اصلی",
  },
  {
    id: 2,
    image: "assets/images/firstPageImages/02.png",
    text: "پیش غذا",
  },
  {
    id: 3,
    image: "assets/images/firstPageImages/03.png",
    text: "دسر",
  },
  {
    id: 4,
    image: "assets/images/firstPageImages/04.png",
    text: "نوشیدنی",
  },
];

// Introduction
export const introductionIcons = [
  {
    id: 1,
    icon: "assets/images/icons/user_02.png",
    text: "پرسنلی مجرب و حرفه‌ای",
  },
  {
    id: 2,
    icon: "assets/images/icons/diagram.png",
    text: "کیفیت بالای غذاها",
  },
  {
    id: 3,
    icon: "assets/images/icons/home-wifi.png",
    text: "محیطی دلنشین و آرام",
  },
  {
    id: 4,
    icon: "assets/images/icons/menu-board.png",
    text: "منوی متنوع",
  },
];

export const footerInformation = [
  {
    id: 1,
    text: "پرسش‌های متداول",
  },
  {
    id: 2,
    text: "قوانین ترخینه",
  },
  {
    id: 3,
    text: "حریم خصوصی",
  },
];
